env:
  node: true
  es6: true

extends: 'eslint:recommended'

rules:
  no-unused-vars: [error, {args: none}]
  no-redeclare: error
  for-direction: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty-character-class: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens: [error, functions]
  no-extra-semi: error
  no-func-assign: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-obj-calls: error
  no-template-curly-in-string: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-negation: error
  use-isnan: error
  valid-typeof: error
  no-undef: error
  func-call-spacing: error
  indent: [error, 2, {ArrayExpression: first,
                      CallExpression: {arguments: first},
                      FunctionDeclaration: {parameters: first},
                      FunctionExpression: {parameters: first},
                      MemberExpression: off,
                      ObjectExpression: first}]